Updated extract_png.cpp
ddpigeon/stegosaurus pull request #9
Opened 2024-04-27 15:43 UTC by Padmavati-123

2024-05-03 10:12 UTC, ddpigeon requested changes

2024-05-03 10:12 UTC, ddpigeon commented on src/extract_png.cpp
> +    bool compression_bit = 0;
`encryption_bit` and `compression_bit` are already defined, you don't need to redefine it

2024-05-03 10:12 UTC, ddpigeon commented on src/extract_png.cpp
General note: `input_buffer.str()` copies the contents to a string, which takes time (especially for larger amounts of data).
 So ideally call `input_buffer.str()` once and then work on that copy instead of calling it multiple times.
something like `string input_str = input_buffer.str()`, then operate on `input_str`.

2024-05-03 10:12 UTC, ddpigeon commented on src/extract_png.cpp
> +            currentindex += chunkSize + 4;
should be `currentindex += (chunkSize + 8)`, since 4 bytes for chunk type which you haven't accounted for, and another 4 bytes of CRC.

2024-05-03 10:12 UTC, ddpigeon commented on src/extract_png.cpp
> +            currentindex += 17;
The way you're trying to read the message size is wrong, you're bypassing all the bits used to store the message here, which isn't the best idea, so remove that line (`currentindex += 17`)

2024-05-03 10:12 UTC, ddpigeon commented on src/extract_png.cpp
> +            currentindex += 4;
This section is wrong, you need to read the last 2 bits of each byte. Reading the last two bits of 4 bytes gives you one byte corresponding to message length. Repeat this 4 times to get message length.

2024-05-03 10:12 UTC, ddpigeon commented on src/extract_png.cpp
> +            currentindex += 4;
```suggestion
            //Something like this
            uint32_t messageSize = 0;
            for (int i = 0; i < 4; i++) {
                uint8_t message_size_byte = 
                ((input_str[currentindex] & 0x03) << 6) |
                ((input_str[currentindex + 1] & 0x03) << 4) |
                ((input_str[currentindex + 2] & 0x03)<< 2) |
                ((input_str[currentindex + 3] & 0x03));
                // gets last 2 bits from 4 bytes.

                messageSize |= message_size_byte << (8 * (3-i));
                //Shifts first byte by 24, second by 16 etc.
                currentindex += 4;
            }

```

2024-05-03 14:43 UTC, Padmavati-123 reviewed
I agree with your suggestions and hence, I have changed the code accordingly.

2024-05-09 13:27 UTC, ddpigeon approved these changes

2024-05-09 13:27 UTC, merged